name: HollisMotorcycles
favicon: null
layout_spectrum: 0.7689827834255993
typography_spectrum: 0.7350629437714815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9958567067515105
  lightness: 0.36486167181283236
  saturation: 0.23481502360664308
  rhythmicContrast: 0.6431837039999664
purpose: []
