name: HollisMotorcycles
favicon: null
layout_spectrum: 0.00386
typography_spectrum: 0.38246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20181d'
    - '#5d5a5b'
    - '#c2bfc0'
    - '#dfdfe1'
    - '#782e16'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
